---
- name: Test routeros_command
  hosts: mikrotik_production_all
  gather_facts: false

  tasks:
    - name: run command on remote devices
      routeros_command:
        commands: /ip ipsec export
      register: ipsec_print
      vars:
        ansible_command_timeout: 30

    - name: debug print
      debug:
        var: ipsec_print.stdout_lines
