---
- name: Test routeros_command
  hosts: mikrotik_production_all
  gather_facts: false

  tasks:
    - name: run command on remote devices
      routeros_command:
        commands: /ip firewall address-list add address=1.1.1.1 list=Trusted
      register: ipaddr_print
      vars:
        ansible_command_timeout: 30

    - name: debug print
      debug:
        var: ipaddr_print.stdout_lines
