---
- name: Add ansible user to mikrotik
  user: mikroansible
  hosts: mikrotik_production_all
  connection: local
  gather_facts: no
  roles:
     - add-to-ansible
  
  vars_prompt:
     - name: "ros_login"
       prompt: "Enter login"
       private: no

     - name: "ros_passwd"
       prompt: "Enter password"
       private: yes
