---
- name: Uninstall software
  hosts: windows
  tasks:
    - name: Uninstall 7zip
      win_package:
        path: C:\Program Files\7-Zip\Uninstall.exe
        product_id: 7-Zip
        arguments: /S
        state: absent
