---

- name: Generate .rsc to check and add user
  template: src=change-admin-password.rsc.j2 dest=roles/change-admin-password/files/tmp/{{inventory_hostname}}.rsc

- name: Run .rsc script
  command: bash -c "cat roles/change-admin-password/files/tmp/{{inventory_hostname}}.rsc | ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}}"  

- name: Delete temp .rsc file
  file: path=roles/change-admin-password/files/tmp/{{inventory_hostname}}.rsc state=absent
