---
- name: Check Mikrotik firewall if blacklist rule exists
  command: bash -c "cat roles/check-blacklist/files/check-blacklist.rsc | ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}}"  
  register: mtblacklist
