---
- name: Check Mikrotik packages version
  #command: bash -c "cat roles/check-version/files/check-version.rsc | ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}}"  
  command: bash -c "cat roles/check-version/files/check-version.rsc | sshpass -p '' ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}} -o StrictHostKeyChecking=no"
  register: mtversion

