---
ansible_mgmt_user: "mikroansible"
ansible_mgmt_user_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeag+FdJrpc48zO3QSboXA4KG6MRZ+gcyq3bXsg4LOakGSlPi0NiED76GsHMNkvXdoLfgyaiBuD4ugAuP3v2sKmifqm25XATT0cYGEZjVq6PN6hJr3zcCfxRo2jnnsEhng2OI4nyRQfGQweoFIYr2DsT54RT73smJQQHG1/3YMjMEy0sQFnvAT4Wg6l3Cxnv5c8ukLuP/x8ahkevnMABqSF6H4ELhWuNY/HR7eXQC+wdbLXDDi/8HrYouH7/WnPIvotm1BRzhsyeDvKhBVuPcm+6GHWiArPR0oTWBIXvH+7hZYTLdmjVEVmpgmILUqVnbRGy2ZSTqJ3v0+DfdbELNB mikroansible@centos02"
